title: Handie
description: UI stuffs for the dashboard of a website
keywords: handie,admin,dashboard,ui,framework
tagline:

collections:
  pages:
    output: true
    permalink: /:path/
  adaptors:
    output: true
    permalink: /:collection/:path/
  admin:
    output: true
    permalink: /:collection/:path/
  cookbook:
    output: true
    permalink: /:collection/:path/
  showcase:
    output: true
    permalink: /:collection/:path/

# Handling Reading
exclude:
  - .asset-cache
  - .sass-cache
  - _admin/vendor/select2/docs
  - _admin/vendor/select2-bootstrap-theme/docs
  - node_modules
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - CNAME
  # - README.md
encoding: utf-8

# Plugins
gems:
  - jekyll-assets
  - jekyll-contentblocks
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll_version_plugin

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: demos
    values:
      layout: default
  - scope:
      path: ""
      type: admin
    values:
      layout: admin
  - scope:
      path: ""
      type: cookbook
    values:
      layout: page
  - scope:
      path: ""
      type: showcase
    values:
      layout: showcase



# =====
# Customized configurations
# =====

# Modules
module:
  comment: true
  share: true
